version: '3.8'
services:
  db-prod:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: game
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    profiles:
      - prod

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    depends_on:
      - db-prod
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - cargo-cache:/usr/local/cargo
    environment:
      DATABASE_URL: "mysql://user:password@db-prod/game"
    profiles:
      - prod

volumes:
  db-data:
  cargo-cache:
