FROM rust:1.76.0 AS builder

WORKDIR /usr/src/app/B4

ENV DOCKERIZE_VERSION v0.6.1

RUN apt-get update && \
    apt-get install -y libmariadb-dev-compat libmariadb-dev wget && \
    rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features mysql
RUN cargo install hurl

CMD ["sleep", "infinity"]