version: '3.8'
services:
  db-prod:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'game'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    profiles:
      - prod
  
  db-dev:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'game'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    profiles:
      - dev

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      HOST: '0.0.0.0'
      PORT: '8080'
      USER_SECRET_KEY: 'user_secret_key'
      ADMIN_SECRET_KEY: 'admin_secret_key'
      DATABASE_URL: mysql://root:root@db-dev/game
    depends_on:
      - db-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/B4
      - cargo-cache:/usr/local/cargo
    profiles:
      - dev
    
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      HOST: '0.0.0.0'
      PORT: '8080'
      USER_SECRET_KEY: 'user_secret_key'
      ADMIN_SECRET_KEY: 'admin_secret_key'
      DATABASE_URL: mysql://root:root@db-prod/game
    depends_on:
      - db-prod
    ports:
      - "8080:8080"
    volumes:
      - cargo-cache:/usr/local/cargo
    profiles:
      - prod

volumes:
  db-data:
  cargo-cache:
